const en = {
  lang: 'en',
  htmlLang: 'en',
  locale: 'en_US',

  meta: {
    title: 'Pedro Castanheira — AI Engineer',
    description:
      'AI engineer and tech lead. LangGraph agents, multi-tenant RAG, MCP servers and LLMOps in production — from data curation to evaluation in CI.',
  },

  ui: {
    skip: 'Skip to content',
    nav: { work: 'Work', graph: 'Evidence', method: 'Method', path: 'Path', contact: 'Contact' },
    langSwitch: { label: 'PT', title: 'Ler em português' },
    home: 'Home',
  },

  hero: {
    eyebrow: 'Pedro Castanheira Costa · AI Engineer · Tech Lead',
    titleBefore: 'I build AI agents that ',
    titleMark: 'run in production',
    titleAfter: ' — from the data to deployment and evaluation.',
    lede:
      'I am the technical lead of a squad responsible for five AI products in production at an education company. I work from problem discovery with business teams through architecture, implementation, observability and evaluation — mostly with Python, LangGraph and FastAPI, and TypeScript with NestJS on the backend.',
    note: 'anonymized products, real numbers',
    metrics: [
      { value: '70–120', label: 'sales a day closed by a conversational agent, 24/7' },
      { value: '~140k', label: 'submissions graded per month by an async pipeline with LangChain' },
      { value: '~45%', label: 'lower OCR cost by discarding invalid documents before extraction' },
    ],
    sketch: {
      data: 'spreadsheets, PDFs,\ninternal systems',
      messy: 'messy data',
      'a-data-ctx': 'curation',
      context: 'reliable\ncontext',
      agent: 'agents\n(LangGraph)',
      tools: 'tools · MCP',
      memory: 'memory',
      prod: 'production\n24/7',
      eval: 'evals in CI\n+ Langfuse',
      'a-eval-ctx': 'measure and adjust',
      me: '↑ this is what I build, end to end',
    },
    sketchLabel: 'Sketch: data goes through curation, becomes context, feeds agents in production, and evaluation flows back into context.',
    ctas: { work: 'See the work', github: 'GitHub', linkedin: 'LinkedIn', contact: 'Get in touch' },
  },

  graph: {
    kicker: 'Evidence',
    title: 'Every skill here points to proof.',
    lede:
      'Instead of a list of technologies, a graph: each skill links to the projects where it was used. Hover, tap or use the keyboard to light up the connections.',
    prodLabel: 'in production',
    personalLabel: 'personal · open source',
    pick: 'Pick a skill',
    provedBy: 'Where I used it',
    skills: {
      langgraph: 'LangGraph',
      curation: 'Data curation',
      context: 'Memory & context',
      rag: 'RAG',
      multitenant: 'Multi-tenant',
      cost: 'Cost per task',
      vision: 'Computer vision',
      multiagent: 'Multi-agent',
      mcp: 'MCP servers',
      evals: 'Evaluation in CI',
      graphs: 'Graphs · Neo4j',
      python: 'Python · FastAPI',
      typescript: 'TypeScript · Node',
      queues: 'Queues & workers',
    },
  },

  work: {
    kicker: 'Work',
    prodTitle: 'In production',
    prodLede: 'Three of the five products I lead technically. The names stay out; the problem, the decisions and the numbers stay in.',
    prodBadge: 'Production',
    personalTitle: 'Personal projects',
    personalLede: 'Where I test ideas in the open: graph-based code review, RAG evaluation and tooling for coding agents.',
    personalBadge: 'Personal · open source',
    read: 'Read the case',
  },

  method: {
    returnLabel: 'evidence feeds back into discovery',
    kicker: 'Method',
    title: 'How an AI product gets built with me.',
    lede: 'The loop I run with my squad. Evaluation and observability feed back into discovery, so the product improves on evidence — not on impressions.',
    steps: [
      { id: 'discovery', label: 'discovery', text: 'Diagnosis with business teams: which decision or task changes, and how we will know it worked.' },
      { id: 'data', label: 'curation', text: 'Understand documents and spreadsheets, relate entities and metadata, decide what the source of truth is.' },
      { id: 'context', label: 'context', text: 'Chunking, hybrid search, context routing and short- and long-term memory.' },
      { id: 'build', label: 'agents', text: 'LangGraph graphs, subagents, tools, API integrations and MCP servers.' },
      { id: 'eval', label: 'evaluation', text: 'Evaluators plus retrieval and full-graph tests running in CI/CD.' },
      { id: 'observe', label: 'operation', text: 'Langfuse, cost, error and hallucination metrics in production.' },
    ],
  },

  path: {
    kicker: 'Path',
    title: 'Where this experience comes from.',
    jobs: [
      {
        role: 'Software Engineer — AI & GenAI · Squad Tech Lead',
        org: 'Inova Soluções Educacionais',
        period: 'Aug 2025 — present',
        current: true,
        bullets: [
          'Technical lead of the squad and of five AI products in production: diagnosis with business teams, architecture, deployment and metrics.',
          'Built LangGraph agents, a grading pipeline on BullMQ and LangChain, a multi-tenant RAG on Qdrant for tutoring and ConvNeXt document classifiers.',
          'Rolled out LLMOps with Langfuse and evaluators; CI/CD with retrieval and full-graph evaluation, plus cost, error and hallucination metrics.',
        ],
      },
      {
        role: 'Data intern',
        org: 'Centro Universitário UniFatecie',
        period: 'May 2025 — Aug 2025',
        bullets: ['Power BI dashboards and queries for Jasper Reports.'],
      },
      {
        role: 'Front-end intern',
        org: 'Vertti Tecnologia',
        period: 'Mar 2025 — May 2025',
        bullets: ['Built features in React and JavaScript.'],
      },
    ],
    educationTitle: 'Education',
    education: {
      degree: 'B.Sc. in Software Engineering',
      school: 'UniCesumar',
      period: 'Feb 2023 — in progress',
    },
    certsTitle: 'Certifications',
    certs: [
      'Model Context Protocol: Advanced Topics — Anthropic',
      'Introduction to Model Context Protocol — Anthropic',
      'Introduction to Agent Skills — Anthropic',
      'AI Fluency: Framework & Foundations — Anthropic',
      'Autonomous Agents Nano Course — FIAP',
    ],
    languagesTitle: 'Languages',
    languages: 'Portuguese (native) · English (advanced, C1)',
  },

  contact: {
    kicker: 'Contact',
    title: "Let's talk about agents, data and AI products.",
    text: 'I am open to AI Engineer roles. Email or LinkedIn is the fastest way to reach me.',
    email: 'pedrocastanhacosta1945@gmail.com',
    copy: 'Copy email',
    copied: 'Copied',
    location: 'Maringá, Brazil',
  },

  casePage: {
    back: 'All work',
    sections: {
      problem: 'Problem',
      data: 'Available data',
      decisions: 'Architecture decisions',
      implementation: 'Implementation',
      result: 'Result',
      limits: 'Limits and lessons',
    },
    role: 'Role',
    stack: 'Stack',
    status: 'Status',
    links: 'Links',
    zoom: 'enlarge diagram',
    close: 'close',
    diagramLabel: 'Architecture diagram, assembled as you read',
    stepLabel: 'step',
    estimate: 'estimate',
    swipe: 'swipe to see the whole diagram →',
    next: 'Next case',
    notFoundTitle: 'This case does not exist.',
    notFoundText: 'The link may have changed. All cases are on the home page.',
  },

  footer: {
    note: 'Diagrams drawn in code with rough.js and Excalifont. No generated images.',
    source: 'Site source',
  },

  cases: [
    {
      slug: 'enrollment-agent',
      kind: 'prod',
      short: 'Sales agent',
      title: 'Sales and enrollment agent',
      summary:
        'Built a conversational LangGraph agent with a router, three subagents and tools integrated with internal systems — it answers course questions and drives enrollment, 24/7.',
      metric: { value: '70–120', label: 'sales a day' },
      context: 'Production · education company',
      role: 'Tech lead · architecture and development',
      status: 'In production, 24/7',
      stack: ['Python', 'FastAPI', 'LangGraph', 'LangChain', 'Qdrant', 'Redis', 'MongoDB', 'Celery', 'Langfuse', 'Cloud Run'],
      problem:
        'Selling a course means answering precisely about prices, subjects, campuses and eligibility rules — information that varies per course and per client. An agent that gets the price or curriculum wrong loses the sale; one that answers generically does not convert.',
      data:
        'The starting point was fragmented documents and spreadsheets: regulations, FAQs, curricula and catalogs with the same information spread across formats. Before any prompt, the work was curation — understand each source, relate the information and decide what was true.',
      decisions: [
        {
          title: 'Curation in two stages',
          text: 'First, the documents were organized into structured chunks, with ingestion scripts for documents and spreadsheets. Then everything moved to a data management platform where prices, subjects and academic information link to the parent entity “course”.',
        },
        {
          title: 'Explicit routing',
          text: 'A router with structured output picks the path for each message: service, enrollment or handoff to a human consultant. Enrollments already in progress follow a deterministic branch that does not depend on the model.',
        },
        {
          title: 'Hybrid search with a cache',
          text: 'Dense and sparse vectors in Qdrant, result fusion and reranking, with category and course filters. A TTL semantic cache avoids repeating search and reranking for equivalent questions.',
        },
        {
          title: 'Memory that outlives the session',
          text: 'Redis holds the active session (STM); MongoDB holds the durable history. When the session expires, context is rebuilt from history and a cheaper model writes the long-term summary (LTM) used in the next conversation.',
        },
      ],
      implementation: [
        'LangGraph graph: router → service, enrollment and notification subagents → final response.',
        'Tools for the knowledge base, campuses, course catalog and eligibility, saving and checking enrollment data, and handoff to a consultant.',
        'Guardrails that check business rules and compare the values quoted in an answer with what the tools returned.',
        'Message buffering, deduplication and time-window spam blocking; remarketing tasks run on Celery, outside the conversation flow.',
        'Golden set with an LLM judge, Langfuse tracing and token and cost logging per conversation.',
      ],
      result: {
        metrics: [{ value: '70–120', label: 'sales a day' }],
        text: 'The agent runs 24/7 and closes 70 to 120 sales a day.',
      },
      limits: [
        'The move from chunks to the “course” entity is shown as an architecture decision — I do not publish an isolated improvement metric between the two versions.',
        'Integrations, client data and prompts stay out for confidentiality.',
      ],
      flow: {
        student: 'student',
        question: '“how much? which subjects?”',
        sources: 'spreadsheets\n+ documents',
        fragmented: 'fragmented, mixed formats',
        v1: 'v1: structured\nchunks',
        v2: 'v2: “course”\nentity',
        price: 'prices',
        subjects: 'subjects',
        academic: 'academic info',
        memory: 'Redis (STM)\nMongoDB (LTM)',
        session: 'session expired →\nLTM summary returns',
        router: 'router',
        sub1: 'service',
        sub2: 'enrollment',
        sub3: 'handoff to consultant',
        tools: 'tools',
        systems: 'hybrid Qdrant\n+ rerank',
        result: '70–120 sales/day',
        result2: 'running 24/7',
      },
    },
    {
      slug: 'grading-pipeline',
      kind: 'prod',
      short: 'Grading at scale',
      title: 'Assignment grading at scale',
      summary:
        'Designed an asynchronous NestJS pipeline on BullMQ that syncs submissions from the LMS, sends each one to LangChain grading and writes the grade and feedback back to Moodle.',
      metric: { value: '~140k', label: 'submissions graded per month' },
      context: 'Production · education company',
      role: 'Tech lead · architecture and development',
      status: 'In production',
      stack: ['TypeScript', 'NestJS', 'BullMQ', 'Redis', 'PostgreSQL', 'MongoDB', 'LangChain', 'Moodle', 'GCS', 'WebSocket'],
      problem:
        'Grade assignments at volume, with consistent criteria, inside the LMS students and teachers already use — without losing submissions when an external service fails or slows down.',
      data: 'Submissions arrive from the LMS as a file or online text, with activity, offering and organization metadata. Files live in Google Cloud Storage.',
      decisions: [
        {
          title: 'A staged pipeline on queues',
          text: 'One job per activity syncs the submissions and creates one job per submission. Each stage — file, analysis, integration — runs on BullMQ workers, outside the request.',
        },
        {
          title: 'Fail without losing work',
          text: 'Analysis jobs retry up to three times with exponential backoff, deduplicate per answer and keep a per-submission state, so stuck work can be re-queued.',
        },
        {
          title: 'AI in a separate service',
          text: 'NestJS orchestrates; LangChain grading runs in its own Python service over HTTP. One side scales the queue; the other evolves the model and the criteria.',
        },
        {
          title: 'Viability measured against the real alternative',
          text: 'Cost per graded assignment was compared with human grading, which is what the product replaces.',
        },
      ],
      implementation: [
        'Cron or manual trigger → activity job → submission sync with the LMS.',
        'BullMQ jobs per submission: file download, call to the grading service and result persistence.',
        'Grade and feedback written back to Moodle.',
        'Events and durations of each run stored for operational dashboards; progress pushed over WebSocket.',
      ],
      result: {
        metrics: [
          { value: '~140k', label: 'submissions graded per month' },
          { value: '~99%', label: 'lower cost per graded assignment vs. human grading', estimate: true },
          { value: '~3,000%', label: 'ROI', estimate: true },
        ],
        text: 'Cost reduction and ROI are internal estimates compared with human grading.',
      },
      limits: [
        'The grading itself is a simple LangChain chain; the hard part is orchestration, resilience and LMS integration.',
        'Cost reduction and ROI are estimates, not audited figures; I do not detail the formula or the period here.',
        'Grading criteria and student data stay out for confidentiality.',
      ],
      flow: {
        trigger: 'cron / manual',
        volume: '~140k submissions/month',
        lms: 'LMS\n(Moodle)',
        activity: 'activity\njob',
        'a-act-lms': 'syncs',
        subs: 'jobs per\nsubmission',
        retry: '3 retries · backoff\n· dedupe · re-queue',
        ai: 'Python service\nLangChain',
        store: 'status +\nresult',
        grade: 'grade +\nfeedback',
        analytics: 'events +\ndurations',
        ws: 'WebSocket',
        r1: '~140k submissions/month',
        r2: '~99% lower cost per assignment vs. human grading (estimate)',
        r3: 'estimated ROI of ~3,000%',
      },
    },
    {
      slug: 'document-triage',
      kind: 'prod',
      short: 'Document triage',
      title: 'Document triage before OCR',
      summary:
        'Built a two-stage visual validator with ConvNeXt-Tiny that discards illegible or wrong-type documents before extraction with Document AI.',
      metric: { value: '~45%', label: 'lower OCR cost' },
      context: 'Production · education company',
      role: 'Model training, serving and integration',
      status: 'In production',
      stack: ['Python', 'FastAPI', 'PyTorch', 'ConvNeXt-Tiny', 'OpenCV', 'NestJS', 'GCP Document AI', 'GCS'],
      problem:
        'OCR and extraction with Document AI are billed per processed page. Without triage, blank, blurry or wrong-type documents pay for OCR and only fail later, at field validation.',
      data:
        'Images and PDFs of personal and academic documents of several types. Training uses labeled positives per type and out-of-scope negatives, with manifests and datasets isolated per type.',
      decisions: [
        {
          title: 'Classify before reading',
          text: 'The documents API calls the validator before OCR. When a document fails, it returns with a reason and Document AI is never called.',
        },
        {
          title: 'Two stages: type and validity',
          text: 'A ConvNeXt-Tiny classifier predicts the type — skipped when the type is already known — and a specialized binary validator decides whether that document is valid.',
        },
        {
          title: 'Spend inference only when needed',
          text: 'A quality gate drops blank, blurry or low-resolution pages before the model. Four-view TTA only kicks in for intermediate confidence, with per-model thresholds.',
        },
        {
          title: 'Serving built for cold starts',
          text: 'Models are cached and warmed at boot, with concurrency capped by a semaphore. On the API side, a 90 s timeout and a retry on cold start.',
        },
      ],
      implementation: [
        'Training pipeline split into corpus, manifests, sampling, training and evaluation, with versioned metrics per model.',
        'A registry that selects version and threshold per document type.',
        'Multi-page documents: up to 8 pages, valid if any page passes, with early accept above 0.97.',
        'Integration in the NestJS API: validation and OCR timed separately; OCR receives the GCS URI.',
      ],
      result: {
        metrics: [
          { value: '~45%', label: 'lower OCR cost on Document AI (GCP)' },
          { value: '98.3%', label: 'type-classifier accuracy on the test split (1,500 images)' },
        ],
        text: 'Invalid documents are discarded before OCR: roughly 45% lower Document AI cost.',
      },
      limits: [
        'Accuracy comes from a versioned test split, not a guarantee on real traffic.',
        'The savings percentage is approximate.',
        'Detailed document types and volumes stay out for confidentiality.',
      ],
      flow: {
        upload: 'document\n(PDF / image)',
        billing: 'Document AI bills\nper processed page',
        dataset: 'positives per type\n+ negatives',
        gate: 'quality gate\n(blank, blur)',
        router: 'ConvNeXt-Tiny\nwhich type?',
        'a-data-router': 'training',
        validator: 'binary validator\nfor the type',
        tta: 'TTA only when unsure',
        reject: 'invalid →\nreturned with reason',
        docai: 'Document AI\n(OCR)',
        'a-val-docai': 'valid',
        fields: 'validated\nfields',
        r1: '~45% lower OCR cost',
        r2: 'classifier: 98.3% on the test split',
      },
    },
    {
      slug: 'cast-review',
      kind: 'personal',
      short: 'Cast Review',
      title: 'Cast Review',
      summary:
        'Built a pull-request review platform that indexes the repository as a Neo4j graph and exposes indexing, context and analysis through an MCP server.',
      metric: { value: '5', label: 'tools on the MCP server' },
      context: 'Personal project · open source',
      role: 'Product, architecture and development',
      status: 'Under active development',
      stack: ['NestJS', 'TypeScript', 'FastAPI', 'LangGraph', 'Neo4j', 'tree-sitter', 'Redis', 'BullMQ', 'MCP SDK', 'React', 'SSE'],
      links: [{ label: 'GitHub', href: 'https://github.com/pedrocastanha/cast-review' }],
      problem:
        'Reviewing only the diff misses the impact outside it: who calls the changed function, which tests cover it, which architectural boundary was crossed.',
      data: 'The repository itself: files, symbols and the relations between them. The diff says what changed; the graph says what that change touches.',
      decisions: [
        {
          title: 'Code as a graph',
          text: 'tree-sitter extracts symbols and relations (defines, references, imports, tests). Neo4j stores the graph per repository and commit, with a Redis lock and incremental re-indexing. Indexing runs outside the request, on a BullMQ queue.',
        },
        {
          title: 'Context on a budget',
          text: 'For the changed files, the AI service assembles related context from the graph within a token budget before calling the reviewers.',
        },
        {
          title: 'Human in the loop',
          text: 'The LangGraph review graph drafts a PRD and a change spec, each with human approval. Once approved, the test and architecture reviewers run in parallel and a report builder consolidates the findings.',
        },
        {
          title: 'MCP as a boundary',
          text: 'A separate MCP server (Streamable HTTP): the opaque token is exchanged for a two-minute acting JWT via introspection, with rate limiting. The tools are a thin proxy to the backend and the AI service.',
        },
      ],
      implementation: [
        'index_repository — triggers incremental indexing of a repository.',
        'get_index_status — reports whether the repository is indexed and its latest indexed commit.',
        'get_related_context — returns the graph context linked to the changed files, within a token budget.',
        'run_pr_analysis — starts an asynchronous PR analysis and returns its analysisId.',
        'get_analysis — fetches the state of a running analysis.',
        'Outside MCP: a repository chat with graph navigation tools (search_symbols, read_symbol, neighbors, list_endpoints, cross_repo_links) and findings published as inline PR comments, with progress over SSE.',
      ],
      implementationTitle: 'MCP server tools',
      result: {
        metrics: [
          { value: '5', label: 'MCP tools' },
          { value: '2', label: 'reviewers in parallel' },
        ],
        text: 'An end-to-end flow, from index to PR comment, available through the web UI and any MCP client — Claude Code, Cursor and others.',
      },
      limits: [
        'Personal project under active development.',
        'Current reviewers cover tests and architecture; other domains do not exist yet.',
        'The MCP server does not edit code: it exposes indexing, context and analysis.',
      ],
      flow: {
        pr: 'Pull\nRequest',
        blind: 'the diff hides who\ndepends on it',
        repo: 'repository',
        queue: 'NestJS +\nBullMQ queue',
        indexer: 'tree-sitter:\nsymbols + relations',
        neo4j: 'Neo4j\ncode graph',
        budget: 'context within\na token budget',
        prd: 'PRD\n+ approval',
        spec: 'spec\n+ approval',
        tests: 'test\nreviewer',
        arch: 'architecture\nreviewer',
        report: 'report\nbuilder',
        github: 'inline PR\ncomments',
        'a-neo-rev': 'context',
        clients: 'Claude Code,\nCursor…',
        mcp: 'MCP server\n5 tools',
        'a-mcp-queue': 'analysis',
        'a-mcp-neo': 'index + context',
        auth: 'opaque token → 2-min JWT · rate limit',
        r: 'from index to PR comment',
      },
    },
    {
      slug: 'rag-groundtruth',
      kind: 'personal',
      short: 'Groundtruth',
      title: 'Groundtruth — an evaluation gate for RAG',
      summary:
        'Built a harness that measures RAG changes before merge and blocks the PR when Recall@10 drops by more than 1 percentage point.',
      metric: { value: '1 pp', label: 'Recall@10 drop is enough to block a merge' },
      context: 'Personal project · open source',
      role: 'Experiment design and development',
      status: 'Complete (V1 and multi-document)',
      stack: ['Python', 'RAGAS', 'GitHub Actions', 'Hybrid search', 'Reranking', 'GraphRAG'],
      links: [{ label: 'GitHub', href: 'https://github.com/pedrocastanha/rag-groundtruth' }],
      problem:
        'Changing chunking, search or the reranker “feels better” until someone measures it. Without a versioned baseline, a retrieval regression reaches production unannounced.',
      data: 'A golden set of 100 human-reviewed questions over one technical document (V1) and 18 approved questions over a three-document corpus (multi-document).',
      decisions: [
        {
          title: 'An objective gate',
          text: 'The baseline is versioned in the repo. A change fails if Recall@10 drops by more than 1 percentage point, with numeric tolerance so rounding does not cause failures.',
        },
        {
          title: 'Prove the test works',
          text: 'A deliberately broken retriever must bring the gate down. If it does not, the gate is useless.',
        },
        {
          title: 'Retrieval and answers measured separately',
          text: 'Recall, MRR and nDCG measure search; Faithfulness and Answer Relevancy (RAGAS) measure the answer. Either one alone is misleading.',
        },
      ],
      implementation: [
        'GitHub Actions workflow that recomputes retrieval and applies the gate.',
        'Comparison of dense, hybrid and LLM-reranked search, at two chunk sizes.',
        'Multi-document: global search, a document-filter tool and graph expansion (GraphRAG), under controlled and tuned conditions, with cost, latency and tool calls per answer.',
      ],
      result: {
        metrics: [
          { value: '0.88 → 0.98', label: 'nDCG@10 with a reranker, Recall within the gate' },
          { value: '−2.78 pp', label: 'Recall with GraphRAG vs. global search: the gate would block it' },
        ],
        text: 'The reranker was recommended as the quality-first option. Graph expansion scored below global search on this sample — and the gate itself would have blocked the merge.',
      },
      limits: [
        'The multi-document golden set is small (18 questions).',
        'Binary relevance cannot tell a direct answer from a passage that only adds context; graded relevance (0–3) would be the next step.',
        'Reranker cost and latency were not compared in V1.',
      ],
      flow: {
        change: 'change:\nchunk, search, reranker',
        feel: '“feels better”…',
        golden: 'golden set\n100 + 18 questions',
        run: 'run\nretrieval',
        metrics: 'Recall@10\nMRR · nDCG',
        baseline: 'versioned\nbaseline',
        gate: 'dropped more\nthan 1 pp?',
        'a-gate-pass': 'no',
        'a-gate-fail': 'yes',
        pass: 'merge',
        fail: 'block',
        ci: 'GitHub Actions',
        ragas: 'RAGAS: faithfulness\n+ relevancy',
        broken: 'retriever broken on\npurpose → gate fails',
        r1: 'reranker: nDCG@10 0.88 → 0.98, Recall within the gate',
      },
    },
    {
      slug: 'cast-code',
      kind: 'personal',
      short: 'Cast Code',
      title: 'Cast Code',
      summary:
        'Built a multi-agent coding CLI that plans, delegates to specialists, uses tools over MCP and checks its own work in the terminal.',
      metric: { value: '~30', label: 'MCP integration templates' },
      context: 'Personal project · open source',
      role: 'Product, architecture and development',
      status: 'Published on npm · evolving',
      stack: ['TypeScript', 'Node.js', 'NestJS', 'MCP', 'WebSocket'],
      links: [
        { label: 'GitHub', href: 'https://github.com/pedrocastanha/cast-code' },
        { label: 'npm', href: 'https://www.npmjs.com/package/cast-code' },
      ],
      problem:
        'Linear assistants write code fast but lose conventions, do not verify the result and break the flow between plan, implementation and delivery.',
      data: 'The local codebase, the Git diff, files and URLs mentioned in the prompt, and the skills and agents defined in the project itself.',
      decisions: [
        {
          title: 'A model per responsibility',
          text: 'Planner, architect, coder and reviewer can use different providers and models, balancing cost and quality per step.',
        },
        {
          title: 'Extensible through files',
          text: 'Skills and agents live in the project as Markdown and are versioned with the code — no changes to the CLI core.',
        },
        {
          title: 'An explicit loop',
          text: 'Plan, act, verify and self-critique before delivering a commit or PR.',
        },
      ],
      implementation: [
        'A main agent that delegates to specialists defined in Markdown (coder, architect, reviewer, tester, frontend, backend, devops and others).',
        'A live tree of subagents in the terminal, with status, current tool and time.',
        'AI Git commands: /up (commit), /split-up (splits commits by intent), /pr and /review.',
        'An MCP client with a template catalog, /remote to follow along in the browser (with voice) and /bridge to run through other providers’ CLIs.',
      ],
      result: {
        metrics: [{ value: 'npm', label: 'published as cast-code' }],
        text: 'Published on npm and continuously evolving.',
      },
      limits: ['Personal project; there are no public usage metrics.'],
      flow: {
        dev: 'you in the\nterminal',
        prompt: 'prompt + @file, @git, URL',
        ctx: 'codebase +\nproject skills',
        core: 'main agent\n(plan)',
        models: 'model per role:\nplanner, coder, reviewer…',
        specialists: 'specialists\n(coder, architect…)',
        tools: 'tools + MCP\n(~30 templates)',
        remote: '/remote: web + voice',
        verify: 'verification:\nreview + tests',
        'a-verify-core': 'self-critique',
        ship: 'commit\n/ PR',
        r: 'published on npm: cast-code',
      },
    },
    {
      slug: 'cast-skills',
      kind: 'personal',
      short: 'Cast Skills',
      title: 'Cast Skills',
      summary:
        'Created an npm package that installs project-context skills and a spec-driven workflow into six AI coding tools.',
      metric: { value: '6', label: 'AI tools supported' },
      context: 'Personal project · open source',
      role: 'Product and development',
      status: 'Published on npm',
      stack: ['Node.js', 'JavaScript', 'SKILL.md', 'npm'],
      links: [
        { label: 'GitHub', href: 'https://github.com/pedrocastanha/cast-skills' },
        { label: 'npm', href: 'https://www.npmjs.com/package/cast-skills' },
      ],
      problem:
        'Coding agents relearn the project every session: they forget conventions, module boundaries and business rules that are not written down anywhere.',
      data: 'The codebase and the team’s answers to a few short bootstrapper questions, turned into a project skill tree.',
      decisions: [
        {
          title: 'An open standard as the source',
          text: 'SKILL.md is the canonical format. Conversion for tools with their own format (Cursor, Windsurf) happens only at install time.',
        },
        {
          title: 'Progressive disclosure',
          text: 'The agent loads the project map first and then only the rules of the module it is touching.',
        },
        {
          title: 'An always-on router',
          text: 'The using-project-skills skill kicks in at the start of any feature, fix or refactor and routes the work through project context and the spec workflow.',
        },
      ],
      implementation: [
        'A wizard (npx cast-skills) that detects installed tools and copies the skills: native SKILL.md for Claude Code, Copilot, Gemini and Codex; converted to .mdc for Cursor and to rules for Windsurf.',
        'Three skills: using-project-skills (router), creating-project-skills (bootstrapper) and explaining-changes (explanations after a change).',
        'Tests with node --test for installation and format conversion.',
      ],
      result: {
        metrics: [{ value: '6', label: 'tools supported' }],
        text: 'Published on npm as cast-skills.',
      },
      limits: ['The token savings quoted in the README are Anthropic’s reference numbers for the skills pattern, not a measurement of this project.'],
      flow: {
        agent: 'coding\nagent',
        forget: 'relearns the project\nevery session',
        codebase: 'codebase +\nteam answers',
        cli: 'npx\ncast-skills',
        tree: 'project\nskill tree',
        native: 'native SKILL.md:\nClaude, Copilot, Gemini, Codex',
        converted: 'converted:\nCursor .mdc, Windsurf',
        router: 'using-project-skills\n(router)',
        work: 'agent with\ncontext',
        r: '6 tools · published on npm',
      },
    },
  ],
};

export default en;
